<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>NEManager.Core</RootNamespace>
    <AssemblyName>NE.Core</AssemblyName>
    <NoWarn>CS1591;CA1401;SYSLIB1054;CS0649;CS0169;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NE.Native\NE.Native.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ICSharpCode.Decompiler" Version="11.0.0.9375" />
    <PackageReference Include="System.Management" Version="8.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="8.0.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>


  <ItemGroup>
    <Using Include="System.Text" />
    <Using Include="System.IO" />
  </ItemGroup>
</Project>
